//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pingod.Local.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pingod.Local.resources.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUSH START.
        /// </summary>
        public static string attract_title {
            get {
                return ResourceManager.GetString("attract_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALL: .
        /// </summary>
        public static string ball_info {
            get {
                return ResourceManager.GetString("ball_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END OF BALL\nBONUS.
        /// </summary>
        public static string bonus {
            get {
                return ResourceManager.GetString("bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDITS.
        /// </summary>
        public static string credits {
            get {
                return ResourceManager.GetString("credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYER {VAL1}\r\nENTER NAME.
        /// </summary>
        public static string high_score_entry {
            get {
                return ResourceManager.GetString("high_score_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIGH SCORES.
        /// </summary>
        public static string high_score_title {
            get {
                return ResourceManager.GetString("high_score_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYER: .
        /// </summary>
        public static string ply_info {
            get {
                return ResourceManager.GetString("ply_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICE MENU.
        /// </summary>
        public static string service_title {
            get {
                return ResourceManager.GetString("service_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio for when resizing the display.
        /// </summary>
        public static string setting_display_aspect_ratio {
            get {
                return ResourceManager.GetString("setting_display_aspect_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS.
        /// </summary>
        public static string setting_display_fps {
            get {
                return ResourceManager.GetString("setting_display_fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FULL SCREEN.
        /// </summary>
        public static string setting_display_fs {
            get {
                return ResourceManager.GetString("setting_display_fs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALWAYS ON TOP.
        /// </summary>
        public static string setting_display_ontop {
            get {
                return ResourceManager.GetString("setting_display_ontop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSYNC.
        /// </summary>
        public static string setting_display_vsync {
            get {
                return ResourceManager.GetString("setting_display_vsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSYNC COMPOSITE.
        /// </summary>
        public static string setting_display_vsynccomp {
            get {
                return ResourceManager.GetString("setting_display_vsynccomp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALLS PER GAME.
        /// </summary>
        public static string setting_game_balls {
            get {
                return ResourceManager.GetString("setting_game_balls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALL SAVE TIME.
        /// </summary>
        public static string setting_game_ballsave_time {
            get {
                return ResourceManager.GetString("setting_game_ballsave_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTRA BALLS MAX.
        /// </summary>
        public static string setting_game_xb_max {
            get {
                return ResourceManager.GetString("setting_game_xb_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MASTER VOLUME.
        /// </summary>
        public static string setting_volume_master {
            get {
                return ResourceManager.GetString("setting_volume_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUSIC VOLUME.
        /// </summary>
        public static string setting_volume_music {
            get {
                return ResourceManager.GetString("setting_volume_music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFX VOLUME.
        /// </summary>
        public static string setting_volume_sfx {
            get {
                return ResourceManager.GetString("setting_volume_sfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOICE VOLUME.
        /// </summary>
        public static string setting_volume_voice {
            get {
                return ResourceManager.GetString("setting_volume_voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLAM TILT.
        /// </summary>
        public static string slam_tilt {
            get {
                return ResourceManager.GetString("slam_tilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TILT.
        /// </summary>
        public static string tilt {
            get {
                return ResourceManager.GetString("tilt", resourceCulture);
            }
        }
    }
}
