//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pingod.Local.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pingod.Local.resources.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUSH START.
        /// </summary>
        public static string attract_title {
            get {
                return ResourceManager.GetString("attract_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALL: .
        /// </summary>
        public static string ball_info {
            get {
                return ResourceManager.GetString("ball_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END OF BALL\nBONUS.
        /// </summary>
        public static string bonus {
            get {
                return ResourceManager.GetString("bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDITS.
        /// </summary>
        public static string credits {
            get {
                return ResourceManager.GetString("credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYER {VAL1}\r\nENTER NAME.
        /// </summary>
        public static string high_score_entry {
            get {
                return ResourceManager.GetString("high_score_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIGH SCORES.
        /// </summary>
        public static string high_score_title {
            get {
                return ResourceManager.GetString("high_score_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYER: .
        /// </summary>
        public static string ply_info {
            get {
                return ResourceManager.GetString("ply_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICE MENU.
        /// </summary>
        public static string service_title {
            get {
                return ResourceManager.GetString("service_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLAM TILT.
        /// </summary>
        public static string slam_tilt {
            get {
                return ResourceManager.GetString("slam_tilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TILT.
        /// </summary>
        public static string tilt {
            get {
                return ResourceManager.GetString("tilt", resourceCulture);
            }
        }
    }
}
